spring:
  application:
    name: REST_SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce
    password: epsont50
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8080

